// generated by stringer -type word main.go; DO NOT EDIT

package main

import "fmt"

const _word_name = "進捗どうですか"

var _word_index = [...]uint8{0, 6, 12, 18, 21}

func (i word) String() string {
	if i < 0 || i+1 >= word(len(_word_index)) {
		return fmt.Sprintf("word(%d)", i)
	}
	return _word_name[_word_index[i]:_word_index[i+1]]
}
